<?php
require_once dirname(__DIR__) . '/includes/auth.php';require_role('COMPANY_REP');$db=db();$rid=current_user()['related_id'];$st=$db->prepare('SELECT company_id FROM company_representative WHERE representative_id=?');$st->execute([$rid]);$cid=(int)$st->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=post('action');
 try{
  if($action==='save'){
   $id=(int)($_POST['job_id']??0);$fairId=(int)$_POST['fair_id'];$title=post('position_title');$type=post('employment_type');$desc=post('job_description');$deadline=normalize_date(post('application_deadline'));$status=post('vacancy_status');
   if($id){
    $db->prepare("UPDATE job_vacancy SET fair_id=?,position_title=?,employment_type=?,job_description=?,application_deadline=TO_DATE(?,'YYYY-MM-DD'),vacancy_status=? WHERE company_id=? AND job_id=?")->execute([$fairId,$title,$type,$desc,$deadline,$status,$cid,$id]);flash('success','Job updated in Oracle.');
   } else {
    $db->prepare("INSERT INTO job_vacancy(job_id,company_id,fair_id,position_title,employment_type,job_description,application_deadline,vacancy_status) VALUES(seq_job.NEXTVAL,?,?,?,?,?,TO_DATE(?,'YYYY-MM-DD'),?)")->execute([$cid,$fairId,$title,$type,$desc,$deadline,$status]);flash('success','Job vacancy created in Oracle.');
   }
  }elseif($action==='delete'){$db->prepare('DELETE FROM job_vacancy WHERE job_id=? AND company_id=?')->execute([(int)$_POST['job_id'],$cid]);flash('success','Job deleted from Oracle.');}
 }catch(Throwable $e){flash('error','Job operation failed: '.oracle_error_message($e));}redirect('company/jobs.php');
}
$edit=null;if(!empty($_GET['edit'])){$x=$db->prepare('SELECT * FROM job_vacancy WHERE job_id=? AND company_id=?');$x->execute([(int)$_GET['edit'],$cid]);$edit=$x->fetch();}
$fairs=$db->prepare("SELECT cf.fair_id,cf.fair_title FROM career_fair cf JOIN company_participation cp ON cp.fair_id=cf.fair_id WHERE cp.company_id=? AND cp.approval_status='APPROVED' ORDER BY cf.event_date");$fairs->execute([$cid]);$fairRows=$fairs->fetchAll();
$jobs=$db->prepare('SELECT j.*,cf.fair_title,(SELECT COUNT(*) FROM application a WHERE a.job_id=j.job_id) applications FROM job_vacancy j JOIN career_fair cf ON cf.fair_id=j.fair_id WHERE j.company_id=? ORDER BY j.job_id DESC');$jobs->execute([$cid]);$rows=$jobs->fetchAll();
$pageTitle='Manage Job Vacancies';include dirname(__DIR__).'/includes/header.php';?>
<div class="card form-card"><h2 style="margin-top:0"><?= $edit?'Edit Job':'Post Job Vacancy' ?></h2><form method="post"><input type="hidden" name="action" value="save"><input type="hidden" name="job_id" value="<?= e((string)($edit['job_id']??'')) ?>"><?= csrf_field() ?><div class="form-grid"><div class="field"><label>Approved Career Fair</label><select name="fair_id" required><?php foreach($fairRows as $f):?><option value="<?= e((string)$f['fair_id']) ?>" <?= (($edit['fair_id']??null)==$f['fair_id'])?'selected':'' ?>><?= e($f['fair_title']) ?></option><?php endforeach;?></select></div><div class="field"><label>Position Title</label><input name="position_title" required value="<?= e($edit['position_title']??'') ?>"></div><div class="field"><label>Employment Type</label><select name="employment_type"><option>FULL_TIME</option><option>PART_TIME</option><option>INTERNSHIP</option><option>CONTRACT</option></select></div><div class="field"><label>Application Deadline</label><input type="date" name="application_deadline" required value="<?= e(input_date($edit['application_deadline']??'')) ?>"></div><div class="field"><label>Status</label><select name="vacancy_status"><option>OPEN</option><option>CLOSED</option></select></div><div class="field full"><label>Job Description</label><textarea name="job_description" required><?= e($edit['job_description']??'') ?></textarea></div></div><div class="actions" style="margin-top:14px"><button class="btn primary">Save Job</button><?php if($edit):?><a class="btn ghost" href="<?= e(url('company/jobs.php')) ?>">Cancel</a><?php endif;?></div></form></div>
<div class="section-title"><h2>Your Job Vacancies</h2></div><div class="table-wrap"><table><thead><tr><th>Position</th><th>Fair</th><th>Deadline</th><th>Status</th><th>Applications</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?= e($r['position_title']) ?></strong><br><span class="muted"><?= e($r['employment_type']) ?></span></td><td><?= e($r['fair_title']) ?></td><td><?= e($r['application_deadline']) ?></td><td><span class="badge <?= badge_class($r['vacancy_status']) ?>"><?= e($r['vacancy_status']) ?></span></td><td><?= e((string)$r['applications']) ?></td><td><div class="actions"><a class="btn small" href="?edit=<?= e((string)$r['job_id']) ?>">Edit</a><form method="post" onsubmit="return confirm('Delete job? Existing applications may prevent deletion.')"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="job_id" value="<?= e((string)$r['job_id']) ?>"><button class="btn small danger">Delete</button></form></div></td></tr><?php endforeach;?></tbody></table></div>
<?php include dirname(__DIR__).'/includes/footer.php'; ?>
