<?php
require_once dirname(__DIR__) . '/includes/auth.php';require_role('COMPANY_REP');$db=db();$rid=current_user()['related_id'];$st=$db->prepare('SELECT company_id FROM company_representative WHERE representative_id=?');$st->execute([$rid]);$cid=(int)$st->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$fid=(int)$_POST['fair_id'];try{$db->prepare("INSERT INTO company_participation(company_id,fair_id,company_registration_date,approval_status) VALUES(?,?,TRUNC(SYSDATE),'PENDING')")->execute([$cid,$fid]);flash('success','Participation request submitted to Oracle.');}catch(Throwable $e){flash('error','Request failed: '.oracle_error_message($e));}redirect('company/participation.php');
}
$fairs=$db->prepare('SELECT cf.*,cp.approval_status,cp.company_registration_date FROM career_fair cf LEFT JOIN company_participation cp ON cp.fair_id=cf.fair_id AND cp.company_id=? ORDER BY cf.event_date');$fairs->execute([$cid]);$rows=$fairs->fetchAll();
$booths=$db->prepare('SELECT b.booth_number,b.location,cf.fair_title,ba.assignment_date FROM booth_assignment ba JOIN booth b ON b.booth_id=ba.booth_id JOIN career_fair cf ON cf.fair_id=b.fair_id WHERE ba.company_id=? ORDER BY cf.event_date');$booths->execute([$cid]);$boothRows=$booths->fetchAll();
$pageTitle='Fair Participation';include dirname(__DIR__).'/includes/header.php';?>
<div class="grid grid-2"><?php foreach($rows as $r):?><div class="card"><div class="split"><h2 style="margin:0"><?= e($r['fair_title']) ?></h2><?php if($r['approval_status']):?><span class="badge <?= badge_class($r['approval_status']) ?>"><?= e($r['approval_status']) ?></span><?php endif;?></div><p class="muted"><?= e($r['event_date']) ?> · <?= e($r['venue']) ?></p><p><?= e($r['description']) ?></p><?php if(!$r['approval_status']):?><form method="post"><?= csrf_field() ?><input type="hidden" name="fair_id" value="<?= e((string)$r['fair_id']) ?>"><button class="btn primary">Request Participation</button></form><?php else:?><div class="help">Requested on <?= e($r['company_registration_date']) ?></div><?php endif;?></div><?php endforeach;?></div>
<div class="section-title"><h2>Assigned Booths</h2></div><div class="table-wrap"><table><thead><tr><th>Fair</th><th>Booth</th><th>Location</th><th>Assigned Date</th></tr></thead><tbody><?php foreach($boothRows as $b):?><tr><td><?= e($b['fair_title']) ?></td><td><strong><?= e($b['booth_number']) ?></strong></td><td><?= e($b['location']) ?></td><td><?= e($b['assignment_date']) ?></td></tr><?php endforeach;?></tbody></table></div>
<?php include dirname(__DIR__).'/includes/footer.php'; ?>
